language: ruby
rvm:
  - 2.3.1
  - 2.2.5
  - 2.1.10
  - 2.0.0
env:
  - DB=postgresql
before_install:
  - cp spec/config.travis.yml spec/config.yml
  - psql -c 'create database textacular_test' -U postgres
script:
  - bundle exec rake db:migrate
  - bundle exec rake
gemfile:
  - Gemfile
  - gemfiles/activerecord-3.2.gemfile
  - gemfiles/activerecord-4.0.gemfile
  - gemfiles/activerecord-4.1.gemfile
  - gemfiles/activerecord-4.2.gemfile

matrix:
  exclude:
    - rvm: 2.0.0
      gemfile: Gemfile
    - rvm: 2.1.10
      gemfile: Gemfile
